config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Shoppe::Engine => "/admin"

  Shoppe::Engine.routes.draw do
    resources :return_forms
    resources :homepage_settings
    resources :sizes
    resources :subscribers
    resources :jobs do
      member do
        get :get_emails_by_job
      end
    end
    resources :stores do
      collection do
        get :import
        post :import
      end
    end
    resources :blogs
    resources :brands
    resources :policies
    resources :careers
    resources :dynamic_options do
      collection do
        get :import
        post :import
      end
    end

    get "orders/export", to: "orders#export"
    post "orders/:id/cancel", to: "orders#cancel", as: "cancel_order"
    post "orders/:id/return", to: "orders#return", as: "return_order"

    get "view_stock", to: "stock_level_adjustments#view_stock", as: "view_stock"
    get "export_stock", to: "stock_level_adjustments#export", as: "export_stock"
    match "import_stock_level_adjustments", to: "stock_level_adjustments#import", as: "import_stock_level_adjustments", via: [:get, :post]
  end

  get 'home/index'
  get "blog/:permalink", to: "blogs#show", as: "blog"
  get "blogs", to: "blogs#index"

  get "product/:permalink", to: "products#show", as: "product"
  post "product/:permalink", to: "products#buy", as: "buy"

  get "brand/:permalink", to: "home#brand_page", as: "brand"
  get "policy/:permalink", to: "home#policy_page", as: "policy"

  get "basket", to: "orders#show"
  delete "basket", to: "orders#destroy"
  post "update_order_items", to: "orders#update_order_items"
  get "get_order_address", to: "orders#get_order_address"

  match "checkout", to: "orders#checkout", as: "checkout", via: [:get]
  match "checkout/details", to: "orders#details", as: "checkout_details", via: [:get, :patch, :post]
  match "checkout/pay", to: "orders#payment", as: "checkout_payment", via: [:get, :post]
  match "checkout/confirm", to: "orders#confirmation", as: "checkout_confirmation", via: [:get, :post]

  match "checkout/confirmation_page", to: "orders#confirmation_page", as: "confirmation_page", via: [:get, :post]
  match "checkout/finalize", to: "orders#finalize", as: "finalize", via: [:get, :post]
  get '/track' => "orders#track"

  get "products", to: "products#index"

  get "videos", to: "home#videos"
  get "faq", to: "home#faq"
  
  get "store_location", to: "home#store_location"
  get "find_nearest_stores", to: "home#find_nearest_stores"
  get "about_us", to: "home#about_us"
  get "contact_us", to: "home#contact_us"
  post '/contact' => "home#contact"
  get "careers", to: "careers#careers"
  post "add_subscriber", to: "home#add_subscriber"
  post "add_careers", to: "careers#add_careers"
  get "/products/sliderprice", to: 'products#sliderprice', as: "slider_price"
  resources :return_forms, only: [:new, :create]

  devise_for :users , :controllers => { :sessions => "sessions", :registrations => "registrations"}

  root to: "home#index"

  get '*not_found', to: 'application#not_found'
end

app/views/shared/_footer.html.erb
<!-- footer  -->
<div class="parallax_footer" >
   <footer  class="navbar  " >
            <div class="container">
               <div class="row botton-20">
                  <center>
                     <div class="footer-widget footer-widget-contacts">
                        <div class="col-md-4"></div>
                        <div class="col-md-4">
                           <h4>SIGN UP FOR NEWSLETTER</h4>
                           <div class="">
                           <%= form_tag "/add_subscriber", :method => :post, :remote=>true, "data-parsley-validate" => true, :id=>"add_subscriber" do %>
                           <button type="submit" title="Subscribe" class="btn btn-default btn-lg  button-grnt"><span><span>Subscribe</span></span></button>
                           <%= text_field_tag :email, params[:email], :class=>"inputnews", :title=>"SIGN UP FOR EMAILS:", :placeholder=>"   Enter Your Email", :required=>true, :autocomplete=> :off, :type=>"email" %>
                           <% end %>
                           </div>
                        </div>
                        <br>
                     </div>
                     <div class="col-md-6">
                        <div class="actions col-md-6">
                        </div>
                  </center>
                  </div>
                  <hr>
                  <div class="col-xs-12 col-sm-3 col-md-3  ">
                     <div class="footer-widget footer-widget-contacts">
                        <h4>EXCHANGE & RETURN</h4>
                        <ul class="list-unstyled" style="line-height: 29px;">
                        <% @policies.try(:each) do |policy| %>
                           <li><a href="<%= policy_path(policy.permalink)%>"> <%= policy.title.capitalize %></a></li>
                        <% end %>
                           <li><a href="/return_forms/new"> Return Merchandise Form </a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-xs-12 col-sm-3 col-md-3 border-left">
                     <div class="footer-widget footer-widget-links">
                        <h4>BRANDS</h4>
                        <ul class="list-unstyled">
                        <% @footer_brands.try(:each) do |brand| %>
                           <li><a href="<%= brand_path(brand.permalink)%>"> <%= brand.name.capitalize %></a></li>
                        <% end %>
                        </ul>
                     </div>
                  </div>
                  <div class="col-xs-12 col-sm-3 col-md-3 border-left">
                     <div class="footer-widget footer-widget-links">
                        <h4>ABOUT</h4>
                        <ul class="list-unstyled">
                           <li><a href="/about_us">The Company</a></li>
                           <li><a href="/store_location">Store Locator</a></li>
                           <li><a href="/contact_us">Contact</a></li>
                           <li><a href="/careers">Careers</a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-xs-12 col-sm-3 col-md-3 border-left">
                     <div class="footer-widget footer-widget-links">
                        <h4>GET IN TOUCH</h4>
                        <ul class="list-unstyled">
                          <!-- <li><a href="tel:+924235241207-8"><i class="fa fa-phone"></i> +92 42 3 5241207-8</a></li>
                           <li>--> <strong> Head office 111-000-174 <br>      
                            E-Marketing +92 42 3 5241207-8<br>
                            </strong>
                            <a href="mailto:customercare@borjan.com.pk" style="text-transform:none !important;">


                           <i class="fa fa-envelope"></i> customercare@borjan.com.pk</a></li>
                           <li><a href="/faq">FAQ</a></li>
                           <div style=" ">
                              <div style=" text-transform: uppercase;
                                 font-weight: bold;
                                 padding-bottom: 8px;"> 
                                 <span style=" font-size:20px;"> 
                                 <a href="https://www.facebook.com/BorjanShoes/
" target="_blank" class="socicallink" title="Borjan Shoes" >
<i class="fa fa-facebook-square " title="Borjan Shoes"></i>  </a> 
<a href="https://www.instagram.com/borjanshoes/" target="_blank"  class="socicallink" ><i class="fa fa-instagram"></i> </a> 
<a href="https://www.twitter.com/borjanshoes1
"  class="socicallink" target="_blank" ><i class="fa fa-twitter"></i> </a>  
<a href="https://www.pinterest.com/borjanshoes1/
"  class="socicallink" target="_blank"> <i class="fa fa-pinterest-square"></i></a> 
<a href="https://plus.google.com/113246613403838508152
" class="socicallink" target="_blank" ><i class="fa fa-google-plus-square"></i> </a>
<a href="mailto:customercare@borjan.com.pk"  class="socicallink" ><i class="fa fa-envelope-o"></i></a>
                                 </span>
                              </div>
                           </div>
                        </ul>
                     </div>
                  </div>
               </div>

               <div class="footer-bottom">
                  <div class="container">
                     <hr>
                     <div class="row">
                        <center>
                           <p class="copyright">© Borjan 2016 All right reserved.</p>
                        </center>
                     </div>
                  </div>
               </div>
            </div>
             <% if Rails.env.production? %>
      <!-- Facebook Pixel Code -->
      <script>
      !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
      n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
      n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
      t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
      document,'script','https://connect.facebook.net/en_US/fbevents.js');

      fbq('init', '1574156832881000');
      fbq('track', "PageView");</script>
      <noscript><img height="1" width="1" style="display:none"
      src="https://www.facebook.com/tr?id=1574156832881000&ev=PageView&noscript=1"
      /></noscript>
      <!-- End Facebook Pixel Code -->
      <!-- Goole analytics -->
                  <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-79882319-1', 'auto');
        ga('send', 'pageview');

      </script>

          <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.6&appId=1344945245522711";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
      <!-- end google -->
          <% end %>
         </footer>

</div>

app/views/shared/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <script type="text/javascript">
    set_toastr_options();
      <%if name == "notice" %>
        toastr.success("<%=msg%>");
      <%else%>
        toastr.error("<%=msg%>");
      <%end%>
    </script>
  <%end%>
<%end%>