config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Shoppe::Engine => "/admin"

  Shoppe::Engine.routes.draw do
    resources :return_forms
    resources :homepage_settings
    resources :sizes
    resources :subscribers
    resources :jobs do
      member do
        get :get_emails_by_job
      end
    end
    resources :stores do
      collection do
        get :import
        post :import
      end
    end
    resources :blogs
    resources :brands
    resources :policies
    resources :careers
    resources :dynamic_options do
      collection do
        get :import
        post :import
      end
    end

    get "orders/export", to: "orders#export"
    post "orders/:id/cancel", to: "orders#cancel", as: "cancel_order"
    post "orders/:id/return", to: "orders#return", as: "return_order"

    get "view_stock", to: "stock_level_adjustments#view_stock", as: "view_stock"
    get "export_stock", to: "stock_level_adjustments#export", as: "export_stock"
    match "import_stock_level_adjustments", to: "stock_level_adjustments#import", as: "import_stock_level_adjustments", via: [:get, :post]
  end

  get 'home/index'
  get "blog/:permalink", to: "blogs#show", as: "blog"
  get "blogs", to: "blogs#index"

  get "product/:permalink", to: "products#show", as: "product"
  post "product/:permalink", to: "products#buy", as: "buy"

  get "brand/:permalink", to: "home#brand_page", as: "brand"
  get "policy/:permalink", to: "home#policy_page", as: "policy"

  get "basket", to: "orders#show"
  delete "basket", to: "orders#destroy"
  post "update_order_items", to: "orders#update_order_items"
  get "get_order_address", to: "orders#get_order_address"

  match "checkout", to: "orders#checkout", as: "checkout", via: [:get]
  match "checkout/details", to: "orders#details", as: "checkout_details", via: [:get, :patch, :post]
  match "checkout/pay", to: "orders#payment", as: "checkout_payment", via: [:get, :post]
  match "checkout/confirm", to: "orders#confirmation", as: "checkout_confirmation", via: [:get, :post]

  match "checkout/confirmation_page", to: "orders#confirmation_page", as: "confirmation_page", via: [:get, :post]
  match "checkout/finalize", to: "orders#finalize", as: "finalize", via: [:get, :post]
  get '/track' => "orders#track"

  get "products", to: "products#index"

  get "videos", to: "home#videos"
  get "faq", to: "home#faq"
  
  get "store_location", to: "home#store_location"
  get "find_nearest_stores", to: "home#find_nearest_stores"
  get "about_us", to: "home#about_us"
  get "contact_us", to: "home#contact_us"
  post '/contact' => "home#contact"
  get "careers", to: "careers#careers"
  post "add_subscriber", to: "home#add_subscriber"
  post "add_careers", to: "careers#add_careers"
  get "/products/sliderprice", to: 'products#sliderprice', as: "slider_price"
  resources :return_forms, only: [:new, :create]

  devise_for :users , :controllers => { :sessions => "sessions", :registrations => "registrations"}

  root to: "home#index"

  get '*not_found', to: 'application#not_found'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @featured_categories = Shoppe::ProductCategory.get_featured_categories
    @new_arrivals = Shoppe::Product.new_arrivals
    @hot_selling = Shoppe::Product.hot_selling
    @homepage_settings = Shoppe::HomepageSetting.slider_records
  end

  def add_subscriber
    @subscriber = Shoppe::Subscriber.new(safe_params)
    @subscriber.save
    @errors = @subscriber.errors.full_messages.join()
  end

  def contact
    Shoppe::UserMailer.delay.contact_us(params)
    flash[:notice] = "Thank you for your message."
    redirect_to "/"
  end

  def store_location
  end

  def find_nearest_stores
    if params[:lat] and params[:lng]
      @stores = Shoppe::Store.near([params[:lat], params[:lng]], 10)
    end
  end

  def brand_page
    @brand = Shoppe::Brand.find_by_permalink(params[:permalink])
  end

  def policy_page
    @policy = Shoppe::Policy.find_by_permalink(params[:permalink])
  end
  
  # def exchange
    
  # end
  
  # def privacy
    
  # end
  
  # def terms
    
  # end

  private

  def safe_params
    params.permit(:email, :contact_no)
  end

end

app/helpers/home_helper.rb
module HomeHelper

  def get_featured_category_class(index)
    if index > 1
      return "col-md-4 col-sm-4 col-xs-4"
    end
    return "col-md-6 col-sm-6 col-xs-6"
  end

  def get_homepage_title(title)
    s = ""
    title = title.split(" ")
    if title.size >= 2
      s << title.first
      s << "<span> #{title.last} </span>"
    else
      s << title.first
    end
    return s.html_safe
  end

  def get_homepage_image(category)
    if category.homepage_image
      return category.try(:homepage_image).try(:path)
    else
      return category.try(:image).try(:path)
    end
  end

end

app/views/home/_featured_block.html.erb
<div style="        background: rgb(238, 237, 239);
   width: 100%;
   padding-top: 50px;
   padding-bottom: 50px;">
   <div class="container" style="padding: 0px;">
      <section class="content categories">
         <center>
            <h2><span style=" color:#333;">Featured </span>Collection</h2>
            <p>
            </p>
         </center>
         <br>
         <div class="row row-no-padding">
         <% @featured_categories.each.with_index do |fc, index| %>
            <!-- CATEGORY - START -->
               <div class="<%= get_featured_category_class(index) %>" >
               <div class="category item-pro">
                  <a href="<%= products_path(category_permalink: fc.permalink) %>" class="">
                     <img src="<%= get_homepage_image(fc) %>" class="img-responsive "  alt="">
                     <div class="item-overlay top"></div>
                     <div class="category-mask"></div>
                     <h3 class="category-title"><%= get_homepage_title(fc.homepage_title) if fc.homepage_title.present? %></h3>
                  </a>
               </div>
            </div>
            <!-- CATEGORY - END -->
            <% if index == 1 %>
               <div style=" margin-bottom: 18px;clear: both;"></div>
            <% end %>
         <% end %>
         </div>
      </section>
   </div>
</div>
<!-- ==========================
   CATEGORIES - END 
   =========================== -->

app/views/home/_footer.html.erb
<!-- footer  -->

<div class="parallax-window" data-parallax="scroll" data-image-src="/assets/footer-img.jpg">
   <footer  class="navbar  " >
            <div class="container">
               <div class="row botton-20">
                  <center>
                     <div class="footer-widget footer-widget-contacts">
                        <div class="col-md-4"></div>
                        <div class="col-md-4">
                           <h4>SIGN UP FOR NEWSLETTER</h4>
                           <div class="">
                           <%= form_tag "/add_subscriber", :method => :post, :remote=>true do %>
                           <button type="submit" title="Subscribe" class="btn btn-default btn-lg  button-grnt"><span><span>Subscribe</span></span></button>
                           <%= text_field_tag :email, params[:email], :class=>"inputnews", :title=>"SIGN UP FOR EMAILS:", :placeholder=>"   Enter Your Email", :required=>true %>
                           <% end %>
                           </div>
                        </div>
                        <br>
                     </div>
                     <div class="col-md-6">
                        <div class="actions col-md-6">
                        </div>
                  </center>
                  </div>
                  <hr>
                  <div class="col-sm-3 col-xs-6  ">
                     <div class="footer-widget footer-widget-contacts">
                        <h4>SHOP</h4>
                        <ul class="list-unstyled" style="line-height: 29px;">
                           <li><a href="#"> Women's Shoes</a></li>
                           <li><a href="#"> Men's Shoes</a></li>
                           <li><a href="#"> Bags</a></li>
                           <li><a href="#"> Accessories</a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-sm-3 col-xs-6 border-left">
                     <div class="footer-widget footer-widget-links">
                        <h4>BRANDS</h4>
                        <ul class="list-unstyled">
                           <li><a href="#">Digger</a></li>
                           <li><a href="#">Skywalk</a></li>
                           <li><a href="#">Gig</a></li>
                           <li><a href="#">Matilla</a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-sm-3 col-xs-6 border-left">
                     <div class="footer-widget footer-widget-links">
                        <h4>ABOUT</h4>
                        <ul class="list-unstyled">
                           <li><a href="/about_us">The Company</a></li>
                           <li><a href="/store_location">Store Locator</a></li>
                           <li><a href="/contact_us">Contact</a></li>
                           <li><a href="/careers">Careers</a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-sm-3 col-xs-6 border-left">
                     <div class="footer-widget footer-widget-links">
                        <h4>GET IN TOUCH</h4>
                        <ul class="list-unstyled">
                           <li><a href="#"><i class="fa fa-phone"></i> +92 00078601</a></li>
                           <li><a href="#"><i class="fa fa-envelope"></i> hello@borjan.com</a></li>
                           <li><a href="#">FAQ</a></li>
                           <div style=" ">
                              <div style=" text-transform: uppercase;
                                 font-weight: bold;
                                 padding-bottom: 8px;;"> <span style=" font-size:20px;"> <i class="fa fa-facebook-square"></i>   <i class="fa fa-twitter"></i>   <i class="fa fa-pinterest-square"></i> <i class="fa fa-google-plus-square"></i> <i class="fa fa-envelope-o"></i>
                                 </span>
                              </div>
                           </div>
                        </ul>
                     </div>
                  </div>
               </div>

               <div class="footer-bottom">
                  <div class="container">
                     <hr>
                     <div class="row">
                        <center>
                           <p class="copyright">© Borjan 2016 All right reserved.</p>
                        </center>
                     </div>
                  </div>
               </div>
            </div>
         </footer>

</div>


<!-- footer end -->
<style type="text/css">
   .modal {
   z-index: 999999 !important;
   }
</style>
<div class="modal modal-fullscreen fade "  tabindex="1" role="dialog" id="modalAdvertising" style="  ">
   <div class="modal-dialog" style="    margin-top: 10%;">
      <div class="modal-content">
         <div class="modal-header">
         </div>
         <div class="modal-body">
            <div class="row">
               <div class="col-sm-12">
                  <center>
                     <h3>Stay Updated!</h3>
                     <p>Enter your email address and get 10% discount for your first purchase.</p>
                     <br>
                  </center>
                  <div class="col-md-2"></div>
                  <div class="col-md-8">
                    <%=form_tag({:controller => :home, :action => :add_subscriber},{:id => "subscription_form", :method => "post", :remote => true, "data-parsley-validate" => true}) do%>   
                    <div class="input-group" style="    width: 100%;
                           margin-bottom: 5px;">
                           <%= text_field_tag :email, params[:email], :class=>"form-control", :placeholder=>"Email Address", :required=>"", :type=>"email" ,:style=>"background: transparent;border: solid 1px;" %>
                        </div>
                        <br>
                        <div class="input-group" style="    width: 100%;
                           margin-bottom: 5px;">
                           <%= text_field_tag :contact_no, params[:contact_no], :class=>"form-control", :placeholder=>"Number", :required=>true ,:style=>"background: transparent;border: solid 1px;" %>
                        </div>
                        <br>
                        <span class="input-group-btn">
                        <button class="btn btn-primary" type="submit" style="float: right;
                           background: transparent;
                           border: solid 1px;">Submit</button>
                        </span>
                     <% end %>
                     <div class="checkbox">  
                        <input id="modal-hide" type="checkbox" value="hidden">  
                        <label for="modal-hide">Don't show this popup again</label>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <div style="clear:both"></div>
      <center>
         <button type="button" class="close" data-dismiss="modal" aria-label="Close">Start</button>
      </center>
   </div>
</div>

<script type="text/javascript">
   $('.parallax-window').parallax({imageSrc: '/assets/footer-img.jpg'});
</script>

app/views/home/_hot_selling.html.erb
<div class="container">
   <div class="row">
      <center>
         <br>
         <h2><span style=" color:#333;">Hot  </span>Selling</h2>
         <p>

         </p>
         <br>
      </center>
      <div id="container" class="cf">
         <div id="main" role="main">
            <section class="slider">
               <div class="flexslider carousel">
                  <ul class="slides">
                     <% @hot_selling.each do |product| %>
                     <%if product.permalink%>
                     <li class="col-md-3">
                        <a href="<%=product_path(product.permalink) %>">
                           <div class="border-shade">
                              <article class="product-item" style="border: solid 1px #fff;">
                              
                               <div class="products-height" >
                                 <img  src="<%= product_image(product) %>" class="" alt="" style="    width: 100%;">
                                 </div>
                               
                                 <h3>
                                    <%= product.name%>
                                 </h3>
                                 <span class="price">
                                 <ins><span class="amount"><%= number_to_currency product.get_price_default_variant %></span></ins>
                                 </span>
                                 <br> <br>
                              </article>
                           </div>
                        </a>
                     </li>
                     <% end %>
                       <% end %>
                  </ul>
               </div>
            </section>
         </div>
      </div>
      <br><br>
      <center>
         <a style="letter-spacing: 8px;" href="<%= products_path(hot_selling: true) %>" class="btn btn-default btn-lg">Shop Now</a>
      </center>
      <div classs="clear-both"></div>
























   </div>
</div>

app/views/home/_main_slider.html.erb
  <div id="flexslider">
    <div class="">
      <ul class="slides">
        <%@homepage_settings.each do |homepage_setting|%>
           <% if homepage_setting.image.present? %>
              <li>
                <div class="container mini-banner"> 
                  <a style="letter-spacing: 8px; " href="<%= products_path(category_permalink: homepage_setting.category_permalink) %>" class="btn btn-default btn-lg ">Shop Now</a>
                </div>
                <img src="<%=homepage_setting.image.path%>" style=" width:100%;" class="img-responsive center-block"/>
              </li>
           <% end %>
        <% end %>
      </ul>
    </div>
  </div>

  <script type="text/javascript">
      $(document).ready(function() {
      $('#flexslider').flexslider({
        animation: "slide"
      });
    });
  </script>

app/views/home/_new_arrivals.html.erb
<!-- ==========================
   GRID PRODUCTS - START 
   =========================== -->
<section class="content grid-products border-top new_background" id="just" >
   <div class="container">
      <div class="row">
         <center>
            <h2><span style=" color:#333;">New </span>Arrivals</h2>
            <p>
            </p>
            <br>
         </center>
         <div id="container" class="cf">
            <div id="main" role="main">
               <section class="slider">
                  <div class="flexslider carousel">
                     <ul class="slides">
                        <% @new_arrivals.each do |product| %>
                        <%if product.permalink%>
                        <li>
                        <a href="<%=product_path(product.permalink) %>">
                           <div class="border-shade">
                              <article class="product-item" style="border: solid 1px #fff;">
                                <div class="products-height" >
                                 <img src="<%= product_image(product) %>" class=" " alt="" style="">
                                 </div>
                                 <h3>
                                    <%= product.name%>
                                 </h3>
                                 <span class="price">
                                 <ins><span class="amount"><%= number_to_currency product.get_price_default_variant%></span></ins>
                                 </span>
                                 <br> <br>
                              </article>
                           </div>
                           </a>
                        </li>
                        <% end %>
                        <% end %>
                     </ul>
                  </div>
               </section>
               <style type="text/css">
                  .flexslider:hover .flex-prev {
                  opacity: 0.8 !important;
                  left: 5px !important;
                  }
                  .flexslider .flex-prev {
                  opacity: 0.8 !important;
                  left: 5px !important;
                  }
               </style>
            </div>
         </div>
         <br><br>
         <center>
            <a style="letter-spacing: 8px;" href="<%= products_path(new_arrivals: true) %>" class="btn btn-default btn-lg">Shop Now</a>
         </center>
         <div classs="clear-both"></div>
      </div>
   </div>
   <br>
   <br>
   <%= render "hot_selling" %>
   <br><br>
</section>

app/views/home/careers.html.erb
  <br><br><br>
  <section class="content products">
    <div class="container">
      <article class="product-item product-single" style="     padding: 20px;">
        <div class="row">
          <br>
          <center>
            <h1>CAREERS</h1>
          </center>
        </div>
        <hr>
      </article>
    </div>
    <div class="container">
      <div class="col-md-2"></div>
      <div class="col-md-8">
      <% @jobs.try(:each) do |job| %>
        <div class="job-post" >
          <center>
            <h2><%= job.name %> </h2>
            <p>
              <%= job.description%>
            </p>
            <button type="button" class="btn btn-default btn-lg" data-toggle="modal" data-target="#applay">apply now</button>
          </center>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-2"></div>
</div>
</section>
<div style="clear:both:"></div>
<br><br>

<div id="applay" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close button-stype" data-dismiss="modal">&times;</button>
        <center>
          <h1 class="modal-title">Apply Now! </h1>
        </center>
      </div>
      <center>
        <div class="modal-body">
          <div class="signin-half">
            <hr>
            <%= form_tag('/add_careers',"data-parsley-validate" => true) do %>
            <%= select_tag(:job_id, options_for_select(Shoppe::Job.all.collect{|m| [m.name, m.id]}), class: "input-checkout") %>
            <%= text_field_tag :first_name, nil, class: "input-checkout", placeholder: "First Name:", required: true%>
            <%= text_field_tag :last_name, nil, class: "input-checkout", placeholder: "Last Name:", required: true%>
            <%= text_field_tag :email, nil, class: "input-checkout", placeholder: "Email", required: true%>
            <%= text_field_tag :contact_no, nil, class: "input-checkout", placeholder: "Contact no", required: true%>
            <%= text_field_tag :cnic_no, nil, class: "input-checkout", placeholder: "NIC", required: true%>
            <%= date_field(:date_of_birth, :date_of_birth, class: "input-checkout", required: true) %>
            <%= select_tag(:gender, options_for_select([["Male", "Male"], ["Female", "Female"]]), class: "input-checkout") %>
            <%= select_tag(:martial_status, options_for_select([["Martial Status", ""], ["Single", "Single"], ["Married", "Married"]]), class: "input-checkout") %>
            <%= text_field_tag :mailing_address, nil, class: "input-checkout", placeholder: "Mailing address"%>
            <%= text_field_tag :city, nil, class: "input-checkout", placeholder: "City"%>
            <h1>Educational Info </h1>
            <%= select_tag(:highest_degree, options_for_select([["Highest Degree", ""], ["Computer IT", "Computer IT"], ["Master", "Master"]]), class: "input-checkout") %>
             <%= select_tag(:institute, options_for_select([["Institute", ""], ["LUMS", "LUMS"], ["FAST", "FAST"], ["COMSATS", "COMSATS"]]), class: "input-checkout") %>
              <%= select_tag(:year_of_completion, options_for_select([["Year of Completion", ""], ["2000", "2000"], ["2001", "2001"]]), class: "input-checkout") %>
               <%= text_field_tag :gpa, nil, class: "input-checkout", placeholder: "CGPA / Grade"%>
               <%= text_field_tag :certification, nil, class: "input-checkout", placeholder: "Certification"%>
               <h1>Employee Info </h1>
               <%= select_tag(:relevant_experice, options_for_select([["Relevant Experice", ""], ["2000", "2000"], ["2001", "2001"]]), class: "input-checkout") %>
               <%= select_tag(:designation, options_for_select([["Title / Designation", ""], ["LUMS", "LUMS"], ["FAST", "FAST"], ["COMSATS", "COMSATS"]]), class: "input-checkout") %>
               <%= text_field_tag :organization, nil, class: "input-checkout", placeholder: "Organization"%>
               <%= text_field_tag :address, nil, class: "input-checkout", placeholder: "Address"%>
               <%= file_field_tag 'attachments[default_image][file]' %>
               <%= hidden_field_tag 'attachments[default_image][role]', 'default_image' %>

            <div style="clear:both"></div>
            <br>
          </div>
          <a href="#" class="btn btn-default">Cancel</a>
           <%= submit_tag("Send", class: "btn btn-default") %>
          <% end %>
        </div>
      </center>
    </div>
  </div>
</div>

app/views/home/contact_us.html.erb
<br><br><br>
<section class="content products">
  <div class="container">
    <article class="product-item product-single" style="     padding: 20px;">
      <div class="row">
        <br>
        <center>
          <h1>CONTACT US</h1>
          <p>Leave us a Message</p>
        </center>
      </div>
      <hr>
    </article>
  </div>
  <div class="container">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="signin-half ">
      <%= form_for :user , :url=> "/contact", :html => {:id => "contact_form", "data-parsley-validate" => true} do |f|%>
        <span class="checkout-bulit">First Name:</span>
        <%= f.text_field :first_name, :class=>"input-checkout", :required=>true %>
        <span class="checkout-bulit">Last Name:</span>
        <%= f.text_field :last_name, :class=>"input-checkout", :required=>true %>
        <span class="checkout-bulit">Email</span>
        <%= f.email_field :email, :class=>"input-checkout", :required=>true %>
        <span class="checkout-bulit">Address </span>
        <%= f.text_field :address, :class=>"input-checkout", :required=>true%>
        <span class="checkout-bulit">Comment </span><br>
        <%= f.text_area :comment, :class=>"input-checkout", :style=>"width: 100%;height: 120px;", :required=>true %>
        <div style="clear:both"></div>
        <br>
        <center>
          <input type="submit" value="Send" class="btn btn-default btn-lg">
        </center>
        <br><br>
        <% end %>
      </div>
    </div>
    <div class="col-md-2"></div>
    <div class="col-md-4">
      
    </div>
    <div class="col-md-4">
     <div class="text-center">
      <h2>Lahore</h2>
      
      <strong><br> Head office 111-000-174 <br>      
      E-Marketing +92 42 3 5241207-8<br>
      customercare@borjan.com.pk</strong>
    </div>
    </div>
    <div class="col-md-4">
      
    </div>
  </div>
</section>
<div style="clear:both:"></div>
<br><br>

app/views/home/exchange.html.erb
  <br><br><br>
  <section class="content products">
    <div class="container">
      <article class="product-item product-single">
        <div class="row">
          <br>
          <center>
            <h1> EXCHANGE &amp; RETURN POLICY </h1>
          </center>
        </div>
        <hr>
      </article>
    </div>
    <div class="container">
      <div class="col-md-12">
<ul>
<li>Products purchased from the Website can be exchanged at the nearest Company&rsquo;s outlets within 7 days from the delivery date by producing the original receipt, provided the products are unused, unworn and undamaged.</li>
<li>At the time of Exchange, the Company will only offer a replacement against products which are available in the outlets.</li>
<li>Please send your inquiries at: customercare@borjan.com.pk or contact us at +92 42 3 5241207-8. Our Customer Care Department will review and respond to your queries as quickly as possible.</li>
<li>The Company&rsquo;s outlet will recover the difference in cash against sale if the value of the replaced product exceeds the original value.</li>
<li>The decision of the Company will be considered final in all scenarios.</li>
</ul>
  
        </div>
    </div>
    <div class="col-md-2"></div>
    </section>
<div style="clear:both:"></div>
<br><br>

app/views/home/find_nearest_stores.js.erb
<% if @stores.present? %>
  <% @stores.each do |store| %>
    var loc = new google.maps.LatLng("<%=store.lat%>", "<%=store.lng%>")
    placeMarker(loc, "<%= store.full_street_address %>");
  <% end %>
<% else %>
  placeMarker(myCenter, "Borjan");
<% end %>

google.maps.event.addListenerOnce(map, 'bounds_changed', function(event) {
    this.setZoom(11);
});

app/views/home/index.html.erb
  <%= render "main_slider" %>

  <%= render "featured_block" %>

  <%= render "new_arrivals" %>

  <%= render "popup_partials/subscribtion_popup"  %>

<script type="text/javascript">
   $(window).load(function () {
      /*------------------------------
         MODAL ADVERTISING
      ------------------------------*/
      if(typeof(Storage) !== "undefined") {
         if(localStorage.getItem("modalhidden") !== "hidden") {
            $('#modalAdvertising').modal('show');
         }
      }
      else {
         $('#modalAdvertising').modal('show');
      }
   });
</script>

app/views/home/privacy.html.erb
  <br><br><br>
  <section class="content products">
    <div class="container">
      <article class="product-item product-single">
        <div class="row">
          <br>
          <center>
            <h1> PRIVACY POLICY </h1>
          </center>
        </div>
        <hr>
      </article>
    </div>
    <div class="container">
      <div class="col-md-12">
<ul>
<li>Borjan respects your concerns about the privacy of your personal information and data security. We do not collect information such as your name, address, phone number, and email address if you view our website as a guest.</li>
<li>You may be asked to provide personal information when you sign up for our newsletter, shop online, enter a contest, participate in a survey, review order history or provide a review about our products.</li>
<li>A cookie is a small piece of information that a website stores on a personal computer and which it can later retrieve. We may use cookies for some administrative purposes, for example, to store our customers' preferences for certain kinds of products or to store a password so that you do not have to input it every time you visit our website. The cookies will not contain information that will enable anyone to contact our customers via telephone, email, or any other means. If our customers are uncomfortable with the use of cookie technology, they can set their browsers to refuse cookies.</li>
<li>We will not share your personal information with any other organization other than related companies and those third parties directly related to the delivery of the products you have purchased from our website and as is necessary to process COD (Cash on Delivery).</li>
<li>We will only keep your information until it serves the purpose for which it was collected or required to by law.</li>
</ul>
  
        </div>
    </div>
    <div class="col-md-2"></div>
    </section>
<div style="clear:both:"></div>
<br><br>

app/views/home/store_location.html.erb
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD8fKrs4Sf14I-hsFjoc9STBPTOwisjAFU" ></script>
<br><br><br>
<section class="content products">
  <div class="container">
    <article class="product-item product-single" style="     padding: 20px;">
      <div class="row">
        <br>
        <center>
          <h1>STORE LOCATOR</h1>
        </center>
      </div>
      <hr>
    </article>
  </div>
  <div class="container">
    <div id="googleMap" style="width:100%;height:500px;">
    </div>
    <br><br><br>
    <div class="text-center">
      <h2>Lahore</h2>
      
      <strong><br> Head office 111-000-174 <br>      
      E-Marketing +92 42 3 5241207-8<br>
      customercare@borjan.com.pk</strong>
    </div>
  </div>
</section>
<div style="clear:both:"></div>
<br><br>
<script>

  var map;
  var marker;
  var infowindow;
  myCenter = new google.maps.LatLng("31.4602775", "74.2753979");

  function initialize(){
  var mapProp = {
    center:myCenter,
    zoom:15,
    mapTypeId:google.maps.MapTypeId.ROADMAP
    };

    map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
    // placeMarker(myCenter, "");
    google.maps.event.addListenerOnce(map, 'idle', function(){
        // console.log('Google map is fully loaded in Gmap V3')
        getLocation();
    });
  }

  google.maps.event.addDomListener(window, 'load', initialize);


</script>