config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Shoppe::Engine => "/admin"

  Shoppe::Engine.routes.draw do
    resources :return_forms
    resources :homepage_settings
    resources :sizes
    resources :subscribers
    resources :jobs do
      member do
        get :get_emails_by_job
      end
    end
    resources :stores do
      collection do
        get :import
        post :import
      end
    end
    resources :blogs
    resources :brands
    resources :policies
    resources :careers
    resources :dynamic_options do
      collection do
        get :import
        post :import
      end
    end

    get "orders/export", to: "orders#export"
    post "orders/:id/cancel", to: "orders#cancel", as: "cancel_order"
    post "orders/:id/return", to: "orders#return", as: "return_order"

    get "view_stock", to: "stock_level_adjustments#view_stock", as: "view_stock"
    get "export_stock", to: "stock_level_adjustments#export", as: "export_stock"
    match "import_stock_level_adjustments", to: "stock_level_adjustments#import", as: "import_stock_level_adjustments", via: [:get, :post]
  end

  get 'home/index'
  get "blog/:permalink", to: "blogs#show", as: "blog"
  get "blogs", to: "blogs#index"

  get "product/:permalink", to: "products#show", as: "product"
  post "product/:permalink", to: "products#buy", as: "buy"

  get "brand/:permalink", to: "home#brand_page", as: "brand"
  get "policy/:permalink", to: "home#policy_page", as: "policy"

  get "basket", to: "orders#show"
  delete "basket", to: "orders#destroy"
  post "update_order_items", to: "orders#update_order_items"
  get "get_order_address", to: "orders#get_order_address"

  match "checkout", to: "orders#checkout", as: "checkout", via: [:get]
  match "checkout/details", to: "orders#details", as: "checkout_details", via: [:get, :patch, :post]
  match "checkout/pay", to: "orders#payment", as: "checkout_payment", via: [:get, :post]
  match "checkout/confirm", to: "orders#confirmation", as: "checkout_confirmation", via: [:get, :post]

  match "checkout/confirmation_page", to: "orders#confirmation_page", as: "confirmation_page", via: [:get, :post]
  match "checkout/finalize", to: "orders#finalize", as: "finalize", via: [:get, :post]
  get '/track' => "orders#track"

  get "products", to: "products#index"

  get "videos", to: "home#videos"
  get "faq", to: "home#faq"
  
  get "store_location", to: "home#store_location"
  get "find_nearest_stores", to: "home#find_nearest_stores"
  get "about_us", to: "home#about_us"
  get "contact_us", to: "home#contact_us"
  post '/contact' => "home#contact"
  get "careers", to: "careers#careers"
  post "add_subscriber", to: "home#add_subscriber"
  post "add_careers", to: "careers#add_careers"
  get "/products/sliderprice", to: 'products#sliderprice', as: "slider_price"
  resources :return_forms, only: [:new, :create]

  devise_for :users , :controllers => { :sessions => "sessions", :registrations => "registrations"}

  root to: "home#index"

  get '*not_found', to: 'application#not_found'
end

app/models/shoppe.rb
module Shoppe
  def self.table_name_prefix
    'shoppe_'
  end
end

app/models/shoppe/address.rb
module Shoppe
  class Address < ActiveRecord::Base
    # An array of all the available types for an address
    ADDRESS_TYPES = %w(permanent current).freeze
    TYPES = %w(billing delivery permanent current).freeze

    # Set the table name
    self.table_name = 'shoppe_addresses'

    # The customer which this address should be linked to
    #
    # @return [Shoppe::Customer]
    belongs_to :customer, class_name: 'Shoppe::Customer'

    # The order which this address should be linked to
    #
    # @return [Shoppe::Order]
    belongs_to :order, class_name: 'Shoppe::Order'

    # The country which this address should be linked to
    #
    # @return [Shoppe::Country]
    belongs_to :country, class_name: 'Shoppe::Country'

    # Validations
    # validates :address_type, presence: true, inclusion: { in: TYPES }
    # validates :address1, presence: true
    # validates :address3, presence: true
    # validates :address4, presence: true
    # validates :postcode, presence: true
    # validates :country, presence: true

    # All addresses ordered by their id asending
    scope :ordered, -> { order(id: :desc) }
    scope :default, -> { where(default: true) }
    scope :billing, -> { where(address_type: 'billing') }
    scope :delivery, -> { where(address_type: 'delivery') }

    def full_address
      [address1, address2, address3, address4, postcode, country.try(:name)].join(', ')
    end
    def self.find_address(customer_id, address_type)
      Shoppe::Address.where(customer_id: customer_id, address_type: address_type).try(:first)
    end
  end
end

app/models/shoppe/attachment.rb
module Shoppe
  class Attachment < ActiveRecord::Base
    # Set the table name
    self.table_name = 'shoppe_attachments'

    # Mount the Carrierwave uploader
    mount_uploader :file, AttachmentUploader

    # Relationships
    belongs_to :parent, polymorphic: true

    # Validations
    validates :file_name, presence: true
    validates :file_type, presence: true
    validates :file_size, presence: true
    validates :file, presence: true
    # validate :check_file_size
    validates :token, presence: true, uniqueness: true

    # All attachments should have a token assigned to this
    before_validation { self.token = SecureRandom.uuid if token.blank? }

    # Set the appropriate values in the model
    before_validation do
      if file
        self.file_name = file.filename if file_name.blank?
        self.file_type = file.content_type if file_type.blank?
        self.file_size = file.size if file_size.blank?
      end
    end


     def check_file_size
      extn = file.file.extension.downcase
      size = file.file.size.to_f
      if ["png", "jpg", "jpeg"].include?(extn) && size > 8.megabytes.to_f
        errors.add(:file, "You cannot upload an image file greater than 5MB")
      else
        errors.add(:file, "You cannot upload a file greater than 25MB")       
      end
    end

    # Return the attachment for a given role
    def self.for(role)
      where(role: role).first
    end

    # Return the path to the attachment
    def path
      file.url
    end

    # Is the attachment an image?
    def image?
      file_type.match(/\Aimage\//).present?
    end
  end
end

app/models/shoppe/blog.rb
class Shoppe::Blog < ActiveRecord::Base

  has_many :attachments, as: :parent, dependent: :destroy, autosave: true, class_name: 'Shoppe::Attachment'
  validates :title, presence: true, uniqueness: true
  validates :permalink, presence: true, uniqueness: true, permalink: true

  before_validation { self.permalink = title.parameterize if permalink.blank? && title.is_a?(String) }

  def attachments=(attrs)
    if attrs['default_image']['file'].present? then attachments.build(attrs['default_image']) end
  end

  def default_image
    attachments.for('default_image')
  end

  def default_image_file=(file)
    attachments.build(file: file, role: 'default_image')
  end
end

app/models/shoppe/brand.rb
class Shoppe::Brand < ActiveRecord::Base

  has_many :attachments, as: :parent, dependent: :destroy, autosave: true, class_name: 'Shoppe::Attachment'
  validates :name, presence: true, uniqueness: true
  validates :permalink, presence: true, uniqueness: true, permalink: true

  before_validation { self.permalink = name.parameterize if permalink.blank? && name.is_a?(String) }


  def attachments=(attrs)
    if attrs['default_image']['file'].present? then attachments.build(attrs['default_image']) end
  end

  def default_image
    attachments.for('default_image')
  end

  def default_image_file=(file)
    attachments.build(file: file, role: 'default_image')
  end

end

app/models/shoppe/career.rb
class Shoppe::Career < ActiveRecord::Base
  belongs_to :job

  has_many :attachments, as: :parent, dependent: :destroy, autosave: true, class_name: 'Shoppe::Attachment'

  GENDER = ["Male", "Female", "Other"]
  MARTIAL_STATUS = ["Single", "Married", "Widow/Widower"]
  YEAR_OF_COMPLETION = (1950..2016).to_a.reverse
  RELEVANT_EXPERICE = (0..50).to_a

  HIGHEST_DEGREE = "Highest Degree"
  INSTITUE = "Institute"
  DESIGNATION = "Designation"
  CITY = "City"

  def attachments=(attrs)
    if attrs['default_image']['file'].present? then attachments.build(attrs['default_image']) end
  end

  def default_image
    attachments.for('default_image')
  end

  def default_image_file=(file)
    attachments.build(file: file, role: 'default_image')
  end

end

app/models/shoppe/customer.rb
module Shoppe
  class Customer < ActiveRecord::Base
    EMAIL_REGEX = /\A\b[A-Z0-9\.\_\%\-\+]+@(?:[A-Z0-9\-]+\.)+[A-Z]{2,6}\b\z/i
    PHONE_REGEX = /\A[+?\d\ \-x\(\)]{7,}\z/

    self.table_name = 'shoppe_customers'

    belongs_to :user, class_name: '::User'

    has_many :addresses, dependent: :restrict_with_exception, class_name: 'Shoppe::Address'
    accepts_nested_attributes_for :addresses

    has_many :orders, dependent: :restrict_with_exception, class_name: 'Shoppe::Order'

    # Validations
    # validates :email, presence: true, uniqueness: true, format: { with: EMAIL_REGEX }
    # validates :phone, presence: true, format: { with: PHONE_REGEX }

    # All customers ordered by their ID desending
    scope :ordered, -> { order(id: :desc) }

    # The name of the customer in the format of "Company (First Last)" or if they don't have
    # company specified, just "First Last".
    #
    # @return [String]
    def name
      company.blank? ? full_name : "#{company} (#{full_name})"
    end

    # The full name of the customer created by concatinting the first & last name
    #
    # @return [String]
    def full_name
      "#{first_name} #{last_name}"
    end

    def self.ransackable_attributes(_auth_object = nil)
      %w(id first_name last_name company email phone mobile) + _ransackers.keys
    end

    def self.ransackable_associations(_auth_object = nil)
      []
    end
  end
end

app/models/shoppe/delivery_service.rb
module Shoppe
  class DeliveryService < ActiveRecord::Base
    self.table_name = 'shoppe_delivery_services'

    # Validations
    # validates :name, presence: true
    # validates :courier, presence: true

    # Orders which are assigned to this delivery service
    has_many :orders, dependent: :restrict_with_exception, class_name: 'Shoppe::Order'

    # Prices for the different levels of service within this delivery service
    has_many :delivery_service_prices, dependent: :destroy, class_name: 'Shoppe::DeliveryServicePrice'

    # All active delivery services
    scope :active, -> { where(active: true) }

    # Returns a tracking URL for the passed order
    #
    # @param order [Shoppe::Order]
    # @return [String] the full URL for the order.
    def tracking_url_for(order)
      return nil if tracking_url.blank?
      tracking_url = self.tracking_url.dup
      tracking_url.gsub!('{{consignment_number}}', CGI.escape(order.consignment_number.to_s))
      tracking_url.gsub!('{{delivery_postcode}}', CGI.escape(order.delivery_postcode.to_s))
      tracking_url.gsub!('{{billing_postcode}}', CGI.escape(order.billing_postcode.to_s))
      tracking_url
    end
  end
end

app/models/shoppe/dynamic_option.rb
require 'roo'
require 'globalize'

class Shoppe::DynamicOption < ActiveRecord::Base
  self.table_name = 'shoppe_dynamic_options'

   OPTIONS_FOR = ["Gender", "Marital Status", "Highest Degree", "Educational Board", "Certificate Programme", "Institute", "Province", "City", "Designation"]

   scope :ordered, -> { order("created_at DESC") }

   validates :title, :options_for, presence: true


   def self.for(options_for)
     where(options_for: options_for)
   end

   def self.array_for(options_for)
     where(options_for: options_for).collect(&:title)
   end

   def self.import(file)
     spreadsheet = open_spreadsheet(file)
     spreadsheet.default_sheet = spreadsheet.sheets.first
     header = spreadsheet.row(1)
     (2..spreadsheet.last_row).each do |i|
       row = Hash[[header, spreadsheet.row(i)].transpose]

       # Don't import dynamic_options where the Title is blank
       next if row['Title'].nil?
       if dynamic_option = where(title: row['Title']).take
         # Dont import dynamic_options with the same Title
       else
         dynamic_option = new
         dynamic_option.title = row['Title']
         dynamic_option.options_for = row['Options For']
         dynamic_option.save!
       end
     end
   end

   def self.open_spreadsheet(file)
     case File.extname(file.original_filename)
     when '.csv' then Roo::CSV.new(file.path)
     when '.xls' then Roo::Excel.new(file.path)
     when '.xlsx' then Roo::Excelx.new(file.path)
     else fail I18n.t('shoppe.imports.errors.unknown_format', filename: File.original_filename)
     end
   end

end

app/models/shoppe/homepage_setting.rb
class Shoppe::HomepageSetting < ActiveRecord::Base
  self.table_name = 'shoppe_homepage_settings'

  has_many :attachments, as: :parent, dependent: :destroy, class_name: 'Shoppe::Attachment'

  scope :slider_records, -> { where(setting_for: "Main Slider").order("position") }

  def attachments=(attrs)
    if attrs['image']['file'].present? then attachments.build(attrs['image']) end
  end

  def image
    attachments.for('image')
  end

  # Set attachment for the image role
  def image_file=(file)
    attachments.build(file: file, role: 'image')
  end

  # @return [Boolean]
  def is_logo?
    setting_for == "Logo"
  end
end

app/models/shoppe/job.rb
class Shoppe::Job < ActiveRecord::Base

  STATUS = [['ENABLED', 1], ['DISABLED', 0]]
  validates :name, :description, presence: true, uniqueness: true
  scope :enabled, -> { where(status: true) }
  scope :last_15_days, -> { where("created_at > ?", 15.days.ago) }
  has_many :careers

end

app/models/shoppe/order/actions.rb
module Shoppe
  class Order < ActiveRecord::Base
    extend ActiveModel::Callbacks

    # These additional callbacks allow for applications to hook into other
    # parts of the order lifecycle.
    define_model_callbacks :confirmation, :acceptance, :rejection, :cancelation, :return

    # This method should be called by the base application when the user has completed their
    # first round of entering details. This will mark the order as "confirming" which means
    # the customer now just must confirm.
    #
    # @param params [Hash] a hash of order attributes
    # @return [Boolean]
    def proceed_to_confirm(params = {})
      self.status = 'confirming'
      if update(params)
        true
      else
        false
      end
    end

    # This method should be executed by the application when the order should be completed
    # by the customer. It will raise exceptions if anything goes wrong or return true if
    # the order has been confirmed successfully
    #
    # @return [Boolean]
    def confirm!
      no_stock_of = order_items.select(&:validate_stock_levels)
      unless no_stock_of.empty?
        fail Shoppe::Errors::InsufficientStockToFulfil, order: self, out_of_stock_items: no_stock_of
      end

      run_callbacks :confirmation do
        # If we have successfully charged the card (i.e. no exception) we can go ahead and mark this
        # order as 'received' which means it can be accepted by staff.
        self.status = 'received'
        self.received_at = Time.now
        save!

        order_items.each(&:confirm!)

        # Send an email to the customer
        deliver_received_order_email
      end

      # We're all good.
      true
    end

    # Mark order as accepted
    #
    # @param user [Shoppe::User] the user who carried out this action
    def accept!(user = nil)
      run_callbacks :acceptance do
        self.accepted_at = Time.now
        self.accepter = user if user
        self.status = 'accepted'
        save!
        order_items.each(&:accept!)
        deliver_accepted_order_email
      end
    end

    # Mark order as rejected
    #
    # @param user [Shoppe::User] the user who carried out the action
    def reject!(user = nil)
      run_callbacks :rejection do
        self.rejected_at = Time.now
        self.rejecter = user if user
        self.status = 'rejected'
        save!
        order_items.each(&:reject!)
        deliver_rejected_order_email
      end
    end

    # Mark order as canceled
    #
    # @param user [Shoppe::User] the user who carried out the action
    def cancel!(user = nil)
      run_callbacks :cancelation do
        self.canceled_at = Time.now
        self.canceler = user if user
        self.status = 'canceled'
        save!
        order_items.each(&:cancel!)
        deliver_canceled_order_email
      end
    end

    # Mark order as canceled
    #
    # @param user [Shoppe::User] the user who carried out the action
    def return!(user = nil)
      # Returned
      run_callbacks :return do
        self.returned_at = Time.now ###
        self.returner = user if user
        self.status = 'returned'
        save!
        order_items.each(&:return!)
        deliver_returned_order_email
      end
    end

    def deliver_accepted_order_email
      Shoppe::OrderMailer.accepted(self).deliver
    end

    def deliver_rejected_order_email
      Shoppe::OrderMailer.rejected(self).deliver
    end

    def deliver_canceled_order_email
      Shoppe::OrderMailer.canceled(self).deliver
    end

    def deliver_returned_order_email
      Shoppe::OrderMailer.returned(self).deliver
    end

    def deliver_received_order_email
      Shoppe::OrderMailer.delay.received(self)
      # Shoppe::OrderMailer.received(self).deliver
    end
  end
end

app/views/shoppe/variants/form.html.haml
- @page_title = "#{t('shoppe.variants.variants')} - #{@product.name}"
= content_for :header do
  %p.buttons
    = link_to t('shoppe.variants.back_to_variants'), [@product, :variants], :class => 'button'
  %h2.products= t('shoppe.variants.variants_of', product:@product.name)

= form_for [@product, @variant], :url => @variant.new_record? ? product_variants_path(@product) : product_variant_path(@product, @variant), :html => {:multipart => true} do |f|
  = f.error_messages
  = field_set_tag t('shoppe.variants.product_information') do
    .splitContainer
      %dl.third
        %dt= f.label :name, t('shoppe.variants.color_name')
        %dd= f.text_field :name, :id=>'colorbox', :class => 'text focus'
      %dl.third
        %dt= f.label :permalink, t('shoppe.variants.permalink')
        %dd= f.text_field :permalink, :class => 'text'
      %dl.third
        %dt= f.label :sku, t('shoppe.variants.sku')
        %dd= f.text_field :sku, :class => 'text'

    .splitContainer
      %dl.third
        %dt= f.label  :color, t('shoppe.variants.color')
        %dd= f.text_field :color,:id => 'color-field', :class => 'text focus jscolor'
  = field_set_tag t('shoppe.variants.product_sizes') do
    %dl
      %dt= f.label :available_sizes, t('shoppe.products.available_sizes')
      %dd= f.collection_select :size_ids, Shoppe::Size.all, :id, :name, {}, {:multiple => true, class: "chosen", :id=>"sizes", :size=>15}


  = field_set_tag t('shoppe.products.attachments') do
    .splitContainer.extraAttachments
      %dl.half
        %dt= f.label "attachments[default_image][file]", t('shoppe.products.default_image')
        %dd
          = attachment_preview @variant.default_image
          %p= f.file_field "attachments[default_image][file]"
          = f.hidden_field "attachments[default_image][role]", value: "default_image"
          = f.hidden_field "attachments[default_image][parent_id]", value: @variant.id

      %dl.half
        %dt= f.label "attachments[default_image][file]", t('shoppe.products.other_images')
        %dd
          = attachment_preview nil, hide_if_blank: false
          %p= f.file_field "attachments[extra][file]", :multiple => true
          = f.hidden_field "attachments[extra][parent_type]", value: "Shoppe::Product"
          = f.hidden_field "attachments[extra][parent_id]", value: @variant.id

      - @variant.attachments.each do |attachment|
        - unless ["default_image", "data_sheet"].include?(attachment.role)
          %dl.half
            %dd
              = attachment_preview attachment

    %p.addAttachments= link_to t('shoppe.products.add_attachments') , '#', :data => {:behavior => 'addAttachmentToExtraAttachments'}, :class => 'button button-mini green'


  = field_set_tag t("shoppe.variants.pricing") do
    .splitContainer
      %dl.third
        %dt= f.label :price, t('shoppe.variants.price')
        %dd
          .moneyInput
            .currency= Shoppe.settings.currency_unit.html_safe
            = f.text_field :price, :class => 'text'
      %dl.third
        %dt= f.label :old_price, t('shoppe.variants.Old_price')
        %dd
          .moneyInput
            .currency= Shoppe.settings.currency_unit.html_safe
            = f.text_field :old_price, :class => 'text' 

  = field_set_tag t('shoppe.variants.stock_control') do
    .splitContainer
      %dl.half
        / %dt= f.label :weight, t('shoppe.variants.weight')
        %dd= f.hidden_field :weight, :class => 'text', :value=>"0.0"
        

      %dl.half
        %dt= f.label :stock_control, t('shoppe.variants.stock_control')
        %dd.checkbox
          = f.check_box :stock_control
          = f.label :stock_control, t('shoppe.variants.enable_stock_control?')

  = field_set_tag t('shoppe.variants.website_properties') do
    .splitContainer
      %dl.half
        %dt= f.label :active, t('shoppe.variants.on_sale?')
        %dd.checkbox
          = f.check_box :active
          = f.label :active, t('shoppe.variants.on_sale_info')
      %dl.half
        %dt= f.label :default, t('shoppe.variants.default_variant?')
        %dd.checkbox
          = f.check_box :default
          = f.label :default, t('shoppe.variants.default_variant_info')

  %p.submit
    - unless @variant.new_record?
      / %span.right= link_to t('shoppe.delete'), product_variant_path(@product, @variant), :class => 'button purple', :method => :delete, :data => {:confirm => t('shoppe.variants.delete_confirmation')}
    = f.submit t('shoppe.variants.save_variant'), :class => 'button green'
    = link_to t('shoppe.cancel'), :products, :class => 'button'

app/views/shoppe/variants/index.html.haml
- @page_title = "#{t('shoppe.variants.variants')} - #{@product.name}"

= content_for :header do
  %p.buttons
    = link_to t('shoppe.variants.edit_product'), [:edit, @product], :class => 'button'
    = link_to t('shoppe.products.view_stock') , view_stock_path(:item_type => @product.class, :item_id => @product.id), :class => 'button', :rel => 'dialog', :data => {:dialog_width => 700}
    = link_to t('shoppe.variants.new_variant'), [:new, @product, :variant], :class => 'button green'

  %h2.products= t('shoppe.variants.variants_of', product: @product.name)

.table
  %table.data
    %thead
      %tr
        %th{:width => '20%'}= t('shoppe.variants.sku')
        %th{:width => '50%'}= t('shoppe.variants.name')
        %th{:width => '15%'}= t('shoppe.variants.price')
        %th{:width => '15%'}= t('shoppe.variants.stock')
    %tbody
      - if @variants.empty?
        %tr.empty
          %td{:colspan => 4}= t('shoppe.variants.no_products')
      - else
        - for variant in @variants
          %tr
            %td= variant.sku
            %td
              = link_to check_for_default_and_active(variant), edit_product_variant_path(@product, variant)
            %td= number_to_currency variant.price
            %td
              - if variant.stock_control?
                %span.float-right= link_to t('shoppe.edit'), stock_level_adjustments_path(:item_type => variant.class, :item_id => variant.id), :class => 'edit', :rel => 'dialog', :data => {:dialog_width => 700, :dialog_behavior => 'stockLevelAdjustments'}
                = boolean_tag(variant.in_stock?, nil, :true_text => variant.stock, :false_text => t('shoppe.variants.no_stock'))
              - else
                &#8734;